### ISSUE TITLE
Multiple users with different permissions

### ISSUE THREAD

**Issue by pragadeeshraju** [Azure-Samples/sftp-creation-template#19]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Hello,

I am not sure whether this is a feature request or documentation issue. (Pardon me)

So here is my requirement,
1) more than one user account
2) different permissions for each account

is it possible that the above req can be done? If so how it can be done?

**Comment by meoukg** [comment]
Hi, I can add multiple user accounts and mount multiple file shares by modifying the template. It would be better and so great if we can restrict the permissions of users. For example: there are 3 users: 
1. **admin**: mount all file shares in the same storage account.
2. **downloader**: only mount the download file share in the same storage account, with the read-only permission, he/she can't upload (write) or delete the files in the download file share, download only.
3. **uploader**: only mount the upload file share in the same storage account, with the write permission, he/she can download, upload (write) and delete the files in the upload file share with any issues.

**Comment by bhummerstone** [comment]
Hi folks! Azure Files currently does not respect permissions and everything mounted into the ACI is set to 777. That said, I haven't played around much with setting permissions after the mount has occurred, so that might be something worth testing; this would need to be scripted via a custom container image as it wouldn't persist between stop/start.

You can specify different UID and GID for each user as part of the environment variable/user.conf, so if you can modify the permissions appropriately you could create the different groups and ensure users are added to the correct groups

**Comment by bhummerstone** [comment]
Closing this issue as it has been idle for a while
